### ------------------------------- 이 구역을 configuration 해주십시오

path_config :
  project_path : /home/wonseok/projects/2022_DATA_SYNTHESIS
  input_path : /home/wonseok/projects/2022_DATA_SYNTHESIS/data/raw
  output_path : /home/wonseok/projects/2022_DATA_SYNTHESIS/data/processed

random_seed : 42
epsilon : [0, 0.1, 1, 10, 100, 1000, 10000]

bayesian_config : 
  degree_of_network : 2
  number_of_tuples : 100
  threshold_value : 20
  mean_observation_days : 1280
  sd_observation_days : 912

colon_file_name : 
  clrc_dg_rcnf : CLRC_DG_RCNF.xlsx
  clrc_ex_diag : CLRC_EX_DIAG.csv
  clrc_oprt_nfrm : CLRC_OPRT_NFRM.xlsx
  clrc_pth_bpsy : CLRC_PTH_BPSY.xlsx
  clrc_pth_mlcr : CLRC_PTH_MLCR.xlsx
  clrc_pth_mnty : CLRC_PTH_MNTY.xlsx
  clrc_pth_srgc : CLRC_PTH_SRGC.xlsx
  clrc_pt_bsnf : CLRC_PT_BSNF.xlsx
  clrc_trtm_casb : CLRC_TRTM_CASB.xlsx
  clrc_trtm_rd : CLRC_TRTM_RD.xlsx
  clrc_dead_nfrm : CLRC_DEAD_NFRM.xlsx


lung_file_name : 
  lung_pt_bsnf : LUNG_PT_BSNF.xlsx
  lung_ex_plmn : LUNG_EX_PLMN.xlsx
  lung_oprt_nfrm : LUNG_OPRT_NFRM.xlsx
  lung_pth_bpsy : LUNG_PTH_BPSY.xlsx
  lung_pth_mlcr : LUNG_PTH_MLCR.xlsx
  lung_pth_mnty : LUNG_PTH_MNTY.xlsx
  lung_pth_srgc : LUNG_PTH_SRGC.xlsx
  lung_trtm_casb : LUNG_TRTM_CASB.xlsx
  lung_trtm_rd : LUNG_TRTM_RD.xlsx
  lung_dead_nfrm : LUNG_DEAD_NFRM.xlsx
  

### -------------------------------- 여기는 건드리지 마시오

colon_config : 
  required : 
    CLRC_DEAD_NFRM:
      DEAD_YMD: datetime64[ns]
      PT_SBST_NO: object
    CLRC_DG_RCNF:
      PT_SBST_NO: object
      RLPS_DIAG_YMD: datetime64[ns]
    CLRC_EX_DIAG:
      CEXM_NM: object
      CEXM_RSLT_CONT: float32
      CEXM_YMD: datetime64[ns]
      PT_SBST_NO: object
    CLRC_OPRT_NFRM:
      OPRT_CLCN_OPRT_KIND_NM: object
      OPRT_CURA_RSCT_NM: object
      OPRT_YMD: datetime64[ns]
      PT_SBST_NO: object
    CLRC_PTH_BPSY:
      BPTH_ACPT_YMD: datetime64[ns]
      BPTH_BPSY_RSLT_CONT: object
      BPTH_CELL_DIFF_NM: object
      PT_SBST_NO: object
    CLRC_PTH_MLCR:
      MLPT_ACPT_YMD: datetime64[ns]
      MLPT_BRME_RSLT_NM: object
      MLPT_KE2E_RSLT_NM: object
      MLPT_KRES_RSLT_NM: object
      MLPT_MSIE_RSLT_NM: object
      MLPT_NREX_RSLT_NM: object
      PT_SBST_NO: object
    CLRC_PTH_MNTY:
      IMPT_ACPT_YMD: datetime64[ns]
      IMPT_HM1E_RSLT_NM: object
      IMPT_HP2E_RSLT_NM: object
      IMPT_HS2E_RSLT_NM: object
      IMPT_HS6E_RSLT_NM: object
      PT_SBST_NO: object
    CLRC_PTH_SRGC:
      PT_SBST_NO: object
      SGPT_ACPT_YMD: datetime64[ns]
      SGPT_CELL_DIFF_NM: object
      SGPT_MTST_LN_CNT: float32
      SGPT_NERV_PREX_NM: object
      SGPT_PATL_M_STAG_VL: object
      SGPT_PATL_N_STAG_VL: object
      SGPT_PATL_T_STAG_VL: object
      SGPT_PATL_STAG_VL: object
      SGPT_SRMG_DCTS_STAT_NM: object
      SGPT_SRMG_PCTS_STAT_NM: object
      SGPT_SRMG_RCTS_STAT_NM: object
      SGPT_SRMV_LN_CNT: float32
      SGPT_TUMR_BUDD_NM: object
      SGPT_VNIN_NM: object
      SGPT_ANIN_NM: object
    CLRC_PT_BSNF:
      BSPT_FRST_DIAG_CD: object
      BSPT_FRST_DIAG_YMD: datetime64[ns]
      BSPT_IDGN_AGE: float32
      BSPT_M_STAG_VL: object
      BSPT_N_STAG_VL: object
      BSPT_SEX_CD: object
      BSPT_STAG_VL: object
      BSPT_T_STAG_VL: object
      PT_SBST_NO: object
    CLRC_TRTM_CASB:
      CSTR_END_YMD: datetime64[ns]
      CSTR_NT: float32
      CSTR_PRPS_NM: object
      CSTR_REGN_NM: object
      CSTR_STRT_YMD: datetime64[ns]
      PT_SBST_NO: object
    CLRC_TRTM_RD:
      PT_SBST_NO: object
      RDT_STRT_YMD: datetime64[ns]
  
  prefix : 
    CLRC_PT_BSNF : PT_BSNF_
    CLRC_EX_DIAG : EX_DIAG_
    CLRC_OPRT_NFRM : OPRT_NFRM_
    CLRC_PTH_BPSY : PTH_BPSY_
    CLRC_PTH_MLCR : PTH_MLCR_
    CLRC_PTH_SRGC : PTH_SRGC_
    CLRC_TRTM_CASB : TRTM_CASB_
    CLRC_TRTM_RD : TRTM_RD_
    CLRC_DG_RCNF : DG_RCNF_
    CLRC_PTH_MNTY : PTH_MNTY_
    CLRC_DEAD_NFRM : DEAD_NFRM_

  derivative : 
    CLRC_OPRT_NFRM :
      parent : [OPRT_CLCN_OPRT_KIND_CD, OPRT_CURA_RSCT_CD] 
      child : [OPRT_CLCN_KIND_NM, OPRT_CURA_RSCT_NM]
    CLRC_PTH_BPSY :
      parent : [BPTH_CELL_DIFF_CD]
      child : [BPTH_CELL_DIFF_NM]
    CLRC_PTH_MLCR :
      parent : [MLPT_MSIE_RSLT_CD, MLPT_KE2E_RSLT_CD, MLPT_KRES_RSLT_CD, MLPT_NREX_RSLT_CD, MLPT_BRME_RSLT_CD]
      child : [MLPT_MSIE_RSLT_NM, MLPT_KE2E_RSLT_NM, MLPT_KRES_RSLT_NM, MLPT_NREX_RSLT_NM, MLPT_BRME_RSLT_NM]
    CLRC_PTH_MNTY :
      parent : [IMPT_HM1E_RSLT_CD, IMPT_HS2E_RSLT_CD, IMPT_HS6E_RSLT_CD, IMPT_HP2E_RSLT_CD]
      child : [IMPT_HM1E_RSLT_NM, IMPT_HS2E_RSLT_NM, IMPT_HS6E_RSLT_NM, IMPT_HP2E_RSLT_NM]
    CLRC_PTH_SRGC :
      parent : [SGPT_CELL_DIFF_CD, SGPT_SRMG_PCTS_STAT_CD, SGPT_SRMG_DCTS_STAT_CD, SGPT_SRMG_RCTS_STAT_CD, SGPT_NERV_PREX_CD, SGPT_VNIN_CD,SGPT_ANIN_CD, SGPT_TUMR_BUDD_CD]
      child : [SGPT_CELL_DIFF_NM, SGPT_SRMG_PCTS_STAT_NM, SGPT_SRMG_DCTS_STAT_NM, SGPT_SRMG_RCTS_STAT_NM, SGPT_NERV_PREX_NM, SGPT_VNIN_NM, SGPT_ANIN_NM, SGPT_TUMR_BUDD_NM]
    CLRC_TRTM_CASB :
      parent : [CSTR_REGN_CD, CSTR_PRPS_CD]
      child : [CSTR_REGN_NM, CSTR_PRPS_NM]
    CLRC_TRTM_RD :
      parent : [RDT_SITD_CD]
      child : [RDT_SITD_NM]

lung_config : 
  required : 
    LUNG_DEAD_NFRM:
      DEAD_YMD: datetime64[ns]
      PT_SBST_NO: object

    LUNG_DG_RCNF:
      PT_SBST_NO: object
      RLPS_DIAG_YMD: datetime64[ns]

    LUNG_EX_DIAG:
      CEXM_NM: object
      CEXM_RSLT_CONT: float32
      CEXM_YMD: datetime64[ns]
      PT_SBST_NO: object
        
    LUNG_OPRT_NFRM:
      OPRT_CLCN_OPRT_KIND_NM: object
      OPRT_CURA_RSCT_NM: object
      OPRT_YMD: datetime64[ns]
      PT_SBST_NO: object

    LUNG_PTH_BPSY:
      BPTH_ACPT_YMD: datetime64[ns]
      BPTH_BPSY_RSLT_CONT: object
      BPTH_CELL_DIFF_NM: object
      PT_SBST_NO: object

    CLRC_PTH_MLCR:
      MLPT_ACPT_YMD: datetime64[ns]
      MLPT_BRME_RSLT_NM: object
      MLPT_KE2E_RSLT_NM: object
      MLPT_KRES_RSLT_NM: object
      MLPT_MSIE_RSLT_NM: object
      MLPT_NREX_RSLT_NM: object
      PT_SBST_NO: object

    CLRC_PTH_MNTY:
      IMPT_ACPT_YMD: datetime64[ns]
      IMPT_HM1E_RSLT_NM: object
      IMPT_HP2E_RSLT_NM: object
      IMPT_HS2E_RSLT_NM: object
      IMPT_HS6E_RSLT_NM: object
      PT_SBST_NO: object

    CLRC_PTH_SRGC:
      PT_SBST_NO: object
      SGPT_ACPT_YMD: datetime64[ns]
      SGPT_CELL_DIFF_NM: object
      SGPT_MTST_LN_CNT: float32
      SGPT_NERV_PREX_NM: object
      SGPT_PATL_M_STAG_VL: object
      SGPT_PATL_N_STAG_VL: object
      SGPT_PATL_T_STAG_VL: object
      SGPT_PATL_STAG_VL: object
      SGPT_SRMG_DCTS_STAT_NM: object
      SGPT_SRMG_PCTS_STAT_NM: object
      SGPT_SRMG_RCTS_STAT_NM: object
      SGPT_SRMV_LN_CNT: float32
      SGPT_TUMR_BUDD_NM: object
      SGPT_VNIN_NM: object
      SGPT_ANIN_NM: object

    LUNG_PT_BSNF:
      PT_SBST_NO: object
      BSPT_SEX_CD: object
      BSPT_BRYM : datetime64[ns]
      BSPT_FRST_DIAG_YMD: datetime64[ns]
      BSPT_FRST_DIAG_CD: object
      BSPT_FRST_DIAG_NM : object
      BSPT_IDGN_AGE: float32
      BSPT_FRST_OPRT_YMD : datetime64[ns]
      BSPT_FRST_ANCN_TRTM_YMD : datetime64[ns]
      BSPT_FRST_RDT_STRT_YMD : datetime64[ns]
      BSPT_DEAD_YMD : datetime64[ns]
      CENTER_LAST_VST_YMD : datetime64[ns]
      OVRL_SRVL_DTRN_DCNT : float32
      BSPT_STAG_VL: object
      BSPT_T_STAG_VL: object
      BSPT_N_STAG_VL: object
      BSPT_M_STAG_VL: object

    LUNG_TRTM_CASB:
      CSTR_END_YMD: datetime64[ns]
      CSTR_NT: float32
      CSTR_PRPS_NM: object
      CSTR_REGN_NM: object
      CSTR_STRT_YMD: datetime64[ns]
      PT_SBST_NO: object

    LUNG_TRTM_RD:
      PT_SBST_NO: object
      RDT_STRT_YMD: datetime64[ns]
  
  prefix : 
    LUNG_PT_BSNF : PT_BSNF_
    LUNG_EX_DIAG : EX_DIAG_
    LUNG_OPRT_NFRM : OPRT_NFRM_
    LUNG_PTH_BPSY : PTH_BPSY_
    LUNG_PTH_MLCR : PTH_MLCR_
    LUNG_PTH_SRGC : PTH_SRGC_
    LUNG_PTH_MNTY : PTH_MNTY_
    LUNG_TRTM_CASB : TRTM_CASB_
    LUNG_TRTM_RD : TRTM_RD_
    LUNG_DEAD_NFRM : DEAD_NFRM_


encodings :
  CLRC_OPRT_NFRM :
    OPRT_CLCN_OPRT_KIND_NM : 
      결장절제술 : 1          
      반흔허니아근본수술 : 2
      소장절제술 : 3          
      장 및 장간막 손상수술 : 4
      장간막종양적출술 : 5
      장관유착박리술 : 6
      장루조성술 : 7          
      장루폐쇄술 : 8          
      장문합술 : 9            
      장폐색증수술 : 10         
      직장 및 에스장절제술 : 11
      직장종양 절제술 : 12     
      직장항문 주위농양수술 : 13
      진단적개복술 : 14        
      충수절제술 : 15         
      후복막종양적출술 : 16
      기타 : 99
    OPRT_CURA_RSCT_NM : 
      해당없음 : 1
      curative : 2
      palliative : 3
      Other : 9
  
  CLRC_PTH_BPSY :
    BPTH_CELL_DIFF_NM : 
      Adenocarcinoma, WD : 1
      Adenocarcinoma, MD : 2
      Adenocarcinoma, PD : 3
      Mucinous ca : 4
      Carcinoid : 5
      Other : 99
  
  CLRC_PTH_MLCR :
    MLPT_MSIE_RSLT_NM : 
      stable : 1
      low : 2
      high : 3
      Other : 9
    MLPT_KE2E_RSLT_NM : 
      not detected : 1
      detected : 2
      Other : 9
    MLPT_KRES_RSLT_NM : 
      not detected : 1
      detected : 2
      Other : 9
    MLPT_NREX_RSLT_NM :
      not detected : 1
      detected : 2
      Other : 9      
    MLPT_BRME_RSLT_NM : 
      not detected : 1
      detected : 2
      Other : 9
  
  CLRC_PTH_MNTY : 
    IMPT_HM1E_RSLT_NM : 
      loss : 1 
      intact : 2
      Other : 9
    IMPP_HS2E_RSLT_NM : 
      loss : 1 
      intact : 2
      Other : 9
    IMPT_HS6E_RSLT_NM : 
      loss : 1 
      intact : 2
      Other : 9
    IMPT_HP2E_RSLT_NM : 
      loss : 1 
      intact : 2
      Other : 9
  
  CLRC_PTH_SRGC : 
    SGPT_CELL_DIFF_NM : 
      Adenocarcinomar, WD : 1
      Adenocarcinoma, MD : 2
      Adenocarcinoma, PD : 3
      Mucinous ca : 4
      Carcinoid : 5
      Other : 99
    
    SGPT_SRMG_PCTS_STAT_NM :
      involved : 1
      uninvolved : 2
      indeterminate : 3
      Other : 9
    
    SGPT_SRMG_DCTS_STAT_NM :
      involved : 1
      uninvolved : 2
      indeterminate : 3
      Other : 9

    SGPT_SRMG_RCTS_STAT_NM :
      involved : 1
      uninvolved : 2
      indeterminate : 3
      Other : 9

    SGPT_NERV_PREX_NM :
      present : 1
      absent : 2
      not identified : 3
      no record : 4
      Other : 9

    SGPT_VNIN_NM :
      present : 1
      absent : 2
      not identified : 3
      no record : 4
      Other : 9
    
    SGPT_ANIN_NM :
      present : 1
      absent : 2
      not identified : 3
      no record : 4
      Other : 9

    SGPT_TUMR_BUDD_NM :
      present : 1
      absent : 2
      not identified : 3
      no record : 4
      Other : 9
  
  CLRC_TRTM_CASB:
    
    CSTR_REGN_NM : 
      none : 1
      5-FU ± leucovorin : 2
      capecitabline : 3
      S-1 : 4
      UFT ± leucovorin : 5
      avastin + fluoropyrimidine(FL/X/UFT/S-1) : 6
      FOLFOX : 7
      FOLFOX + AVASTIN : 8
      FOLFOX + ERBITUX : 9
      XELOX : 10
      XELOX + AVASTIN : 11
      XELOX + ERBITUX : 12
      FOLFIRI : 13
      FOLFIRI + AVASTIN : 14
      FOLFIRI + ERBITUX : 15
      Other : 99
    
    CSTR_PRPS_NM :
      Neo-adjuvant : 1
      Adjuvant : 2
      Palliative : 3 
      Concurrent : 4
      Induction : 5
      Maintenance : 6 
      Salvage : 7
      Consolidation : 8
      Other : 99

institution_specific_columns :
  - CENTER_CD
  - IRB_APRV_NO
  - CRTN_DT

